#!/bin/sh

set -ex

cd /app
bundle install -j4 --retry 3 
bundle clean --force
rm -rf /usr/local/bundle/cache/*.gem
find /usr/local/bundle/gems/ -name "*.c" -delete
find /usr/local/bundle/gems/ -name "*.o" -delete

