# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.6'

gem 'bcrypt'
gem 'bootsnap', require: false
gem 'exception_notification'
gem 'fast_jsonapi'
gem 'image_processing'
gem 'liquid'
gem 'pg'
gem 'puma'
gem 'rails'
gem 'redis'
gem 'sassc-rails'
gem 'sidekiq'
gem 'sidekiq-failures'
gem 'slim-rails'
gem 'turbolinks'
gem 'webpacker'

group :development, :test do
  gem 'byebug'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-rubocop', require: false
end

group :development do
  gem 'spring'
  gem 'spring-watcher-listen'
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'rspec-its'
  gem 'rspec-rails'
  gem 'selenium-webdriver'
  gem 'simplecov'
  gem 'simplecov-lcov'
end

group :code_quality do
  gem 'rubocop', require: false
  gem 'rubocop-rails', require: false
  gem 'rubocop-rspec', require: false
  gem 'undercover', require: false
end
